# Generated by Django 3.2.7 on 2021-09-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='job',
        ),
    ]
